package main

import (
	"fmt"

	"github.com/01-edu/z01"

	"piscine"
)

func main() {
	fmt.Println("Test Case")
	fmt.Println("Hello!")
	fmt.Println("Result :")
	z01.PrintRune(piscine.FirstRune("Hello!"))
	fmt.Println("Test Case")
	fmt.Println("Salut!")
	fmt.Println("Result :")
	z01.PrintRune(piscine.FirstRune("Salut!"))
	fmt.Println("Test Case")
	fmt.Println("Ola!")
	fmt.Println("Result :")
	z01.PrintRune(piscine.FirstRune("Ola!"))
	z01.PrintRune('\n')
	z01.PrintRune('\n')
	fmt.Println("Test Case")
	fmt.Println("Hello!")
	fmt.Println("Result :")
	z01.PrintRune(piscine.LastRune("Hello!"))
	fmt.Println("Test Case")
	fmt.Println("Salut!")
	fmt.Println("Result :")
	z01.PrintRune(piscine.LastRune("Salut!"))
	fmt.Println("Test Case")
	fmt.Println("Ola!")
	fmt.Println("Result :")
	z01.PrintRune(piscine.LastRune("Ola!"))
	fmt.Println("Test Case")
	fmt.Println("SALAM")
	fmt.Println("Result :")
	z01.PrintRune(piscine.LastRune("SALAM"))
	fmt.Println("Test Case")
	fmt.Println("Ola!0101")
	fmt.Println("Result :")
	z01.PrintRune(piscine.LastRune("Ola!0101"))
	z01.PrintRune('\n')
	z01.PrintRune('\n')
	fmt.Println("Test Case")
	fmt.Println("Hello! , 3")
	fmt.Println("Result :")
	z01.PrintRune(piscine.NRune("Hello!", 3))
	fmt.Println("Test Case")
	fmt.Println("Salut! , 2")
	fmt.Println("Result :")
	z01.PrintRune(piscine.NRune("Salut!", 2))
	fmt.Println("Test Case")
	fmt.Println("Bye! , -1")
	fmt.Println("Result :")
	z01.PrintRune(piscine.NRune("Bye!", -1))
	fmt.Println("Test Case")
	fmt.Println("♥01! , 1")
	fmt.Println("Result :")
	z01.PrintRune(piscine.NRune("♥01!", 1))
	fmt.Println("Test Case")
	fmt.Println("Ola! , 4")
	fmt.Println("Result :")
	z01.PrintRune(piscine.NRune("Ola!", 4))
	z01.PrintRune('\n')
	z01.PrintRune('\n')
	fmt.Println("Test Case")
	fmt.Println("Hello!, Hello!")
	fmt.Println("Result :")
	fmt.Println(piscine.Compare("Hello!", "Hello!"))
	fmt.Println("Test Case")
	fmt.Println("Salut!, lut!")
	fmt.Println("Result :")
	fmt.Println(piscine.Compare("Salut!", "lut!"))
	fmt.Println("Test Case")
	fmt.Println("Ola!, Ol")
	fmt.Println("Result :")
	fmt.Println(piscine.Compare("Ola!", "Ol"))
	z01.PrintRune('\n')

	sa := "Hello 78 World!    4455 /"
	sb := " "
	sc := "1234567890"

	nba := piscine.AlphaCount(sa)
	fmt.Println("Test Case")
	fmt.Println("Hello 78 World!    4455 /")
	fmt.Println("Result :")
	fmt.Println(nba)
	nbb := piscine.AlphaCount(sb)
	fmt.Println("Test Case")
	fmt.Println(" ")
	fmt.Println("Result :")
	fmt.Println(nbb)
	nbc := piscine.AlphaCount(sc)
	fmt.Println("Test Case")
	fmt.Println("1234567890")
	fmt.Println("Result :")
	fmt.Println(nbc)
	z01.PrintRune('\n')
	fmt.Println("Test Case")
	fmt.Println("Hello!, l")
	fmt.Println("Result :")
	fmt.Println(piscine.Index("Hello!", "l"))
	fmt.Println("Test Case")
	fmt.Println("Salut!, alu")
	fmt.Println("Result :")
	fmt.Println(piscine.Index("Salut!", "alu"))
	fmt.Println("Test Case")
	fmt.Println("Ola!, hOl")
	fmt.Println("Result :")
	fmt.Println(piscine.Index("Ola!", "hOl"))
	z01.PrintRune('\n')
	fmt.Println("Test Case")
	fmt.Println("Hello!, How are you?")
	fmt.Println("Result :")
	fmt.Println(piscine.Concat("Hello!", " How are you?"))
	fmt.Println("Test Case")
	fmt.Println("Salam , alaykum!")
	fmt.Println("Result :")
	fmt.Println(piscine.Concat("Salam ", "alaykum!"))
	z01.PrintRune('\n')
	fmt.Println("Test Case")
	fmt.Println("HELLO")
	fmt.Println("Result :")
	fmt.Println(piscine.IsUpper("HELLO"))
	fmt.Println("Test Case")
	fmt.Println("HELLO!")
	fmt.Println("Result :")
	fmt.Println(piscine.IsUpper("HELLO!"))
	z01.PrintRune('\n')
	fmt.Println("Test Case")
	fmt.Println("hello")
	fmt.Println("Result :")
	fmt.Println(piscine.IsLower("hello"))
	fmt.Println("Test Case")
	fmt.Println("hello!")
	fmt.Println("Result :")
	fmt.Println(piscine.IsLower("hello!"))
	z01.PrintRune('\n')
	fmt.Println("Test Case")
	fmt.Println("Hello! How are you?")
	fmt.Println("Result :")
	fmt.Println(piscine.IsAlpha("Hello! How are you?"))
	fmt.Println("Test Case")
	fmt.Println("HelloHowareyou")
	fmt.Println("Result :")
	fmt.Println(piscine.IsAlpha("HelloHowareyou"))
	fmt.Println("Test Case")
	fmt.Println("What's this 4?")
	fmt.Println("Result :")
	fmt.Println(piscine.IsAlpha("What's this 4?"))
	fmt.Println("Test Case")
	fmt.Println("Whatsthis4")
	fmt.Println("Result :")
	fmt.Println(piscine.IsAlpha("Whatsthis4"))
	fmt.Println("Test Case")
	fmt.Println("What's this 01?")
	fmt.Println("Result :")
	fmt.Println(piscine.IsAlpha("What's this 01?"))
	fmt.Println("Test Case")
	fmt.Println("ThisIs01")
	fmt.Println("Result :")
	fmt.Println(piscine.IsAlpha("ThisIs01"))
	fmt.Println("Test Case")
	fmt.Println("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890!")
	fmt.Println("Result :")
	fmt.Println(piscine.IsAlpha("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890!"))
	z01.PrintRune('\n')
	fmt.Println("Test Case")
	fmt.Println("010203")
	fmt.Println("Result :")
	fmt.Println(piscine.IsNumeric("010203"))
	fmt.Println("Test Case")
	fmt.Println("01,02,03")
	fmt.Println("Result :")
	fmt.Println(piscine.IsNumeric("01,02,03"))
	fmt.Println("Test Case")
	fmt.Println("0123456789")
	fmt.Println("Result :")
	fmt.Println(piscine.IsNumeric("0123456789"))
	fmt.Println("Test Case")
	fmt.Println("01234a56789")
	fmt.Println("Result :")
	fmt.Println(piscine.IsNumeric("01234a56789"))
	z01.PrintRune('\n')
	fmt.Println("Test Case")
	fmt.Println("Hello")
	fmt.Println("Result :")
	fmt.Println(piscine.IsPrintable("Hello"))
	fmt.Println("Test Case")
	fmt.Println("Hello\\n")
	fmt.Println("Result :")
	fmt.Println(piscine.IsPrintable("Hello\n"))
	fmt.Println("Test Case")
	fmt.Println("\\n\\t")
	fmt.Println("Result :")
	fmt.Println(piscine.IsPrintable("\n\t"))
	z01.PrintRune('\n')
	fmt.Println("Test Case")
	fmt.Println("Hello! How are you?")
	fmt.Println("Result :")
	fmt.Println(piscine.ToUpper("Hello! How are you?"))
	fmt.Println("Test Case")
	fmt.Println("hello")
	fmt.Println("Result :")
	fmt.Println(piscine.ToUpper("hello"))
	z01.PrintRune('\n')
	fmt.Println("Test Case")
	fmt.Println("Hello! How are you?")
	fmt.Println("Result :")
	fmt.Println(piscine.ToLower("Hello! How are you?"))
	fmt.Println("Test Case")
	fmt.Println("HELLO")
	fmt.Println("Result :")
	fmt.Println(piscine.ToLower("HELLO"))
	z01.PrintRune('\n')
	fmt.Println("Test Case")
	fmt.Println("321")
	fmt.Println("Result :")
	piscine.PrintNbrInOrder(321)
	z01.PrintRune('\n')
	fmt.Println("Test Case")
	fmt.Println("0")
	fmt.Println("Result :")
	piscine.PrintNbrInOrder(0)
	z01.PrintRune('\n')
	fmt.Println("Test Case")
	fmt.Println("975301")
	fmt.Println("Result :")
	piscine.PrintNbrInOrder(975301)
	z01.PrintRune('\n')
	fmt.Println("Test Case")
	fmt.Println("2147483647")
	fmt.Println("Result :")
	piscine.PrintNbrInOrder(2147483647)
	z01.PrintRune('\n')
	fmt.Println("Test Case")
	fmt.Println("321321")
	fmt.Println("Result :")
	piscine.PrintNbrInOrder(321321)
	z01.PrintRune('\n')
	z01.PrintRune('\n')
	fmt.Println("Test Case")
	fmt.Println("12345")
	fmt.Println("Result :")
	fmt.Println(piscine.TrimAtoi("12345"))
	fmt.Println("Test Case")
	fmt.Println("str123ing45")
	fmt.Println("Result :")
	fmt.Println(piscine.TrimAtoi("str123ing45"))
	fmt.Println("Test Case")
	fmt.Println("012 345")
	fmt.Println("Result :")
	fmt.Println(piscine.TrimAtoi("012 345"))
	fmt.Println("Test Case")
	fmt.Println("Hello World!")
	fmt.Println("Result :")
	fmt.Println(piscine.TrimAtoi("Hello World!"))
	fmt.Println("Test Case")
	fmt.Println("sd+x1fa2W3s4")
	fmt.Println("Result :")
	fmt.Println(piscine.TrimAtoi("sd+x1fa2W3s4"))
	fmt.Println("Test Case")
	fmt.Println("sd-x1fa2W3s4")
	fmt.Println("Result :")
	fmt.Println(piscine.TrimAtoi("sd-x1fa2W3s4"))
	fmt.Println("Test Case")
	fmt.Println("sdx1-fa2W3s4")
	fmt.Println("Result :")
	fmt.Println(piscine.TrimAtoi("sdx1-fa2W3s4"))
	fmt.Println("Test Case")
	fmt.Println("sdx1+fa2W3s4")
	fmt.Println("Result :")
	fmt.Println(piscine.TrimAtoi("sdx1+fa2W3s4"))
	fmt.Println("Test Case")
	fmt.Println("123-4asd")
	fmt.Println("Result :")
	fmt.Println(piscine.TrimAtoi("123-4asd"))
	z01.PrintRune('\n')
	fmt.Println("Test Case")
	fmt.Println("Hello! How are you? How+are+things+4you?")
	fmt.Println("Result :")
	fmt.Println(piscine.Capitalize("Hello! How are you? How+are+things+4you?"))
	fmt.Println("Test Case")
	fmt.Println("heLLo! how are you? fine, thAnks.")
	fmt.Println("Result :")
	fmt.Println(piscine.Capitalize("heLLo! how are you? fine, thAnks."))
	fmt.Println("Test Case")
	fmt.Println("a")
	fmt.Println("Result :")
	fmt.Println(piscine.Capitalize("a"))
	fmt.Println("Test Case")
	fmt.Println("z")
	fmt.Println("Result :")
	fmt.Println(piscine.Capitalize("z"))
	fmt.Println("Test Case")
	fmt.Println("33@01")
	fmt.Println("Result :")
	fmt.Println(piscine.Capitalize("33@01"))
	fmt.Println("Test Case")
	fmt.Println("9a LALALA!")
	fmt.Println("Result :")
	fmt.Println(piscine.Capitalize("9a LALALA!"))
	fmt.Println("")
}
